module.exports = (email) => {
  return `
  <div style="
    margin:0;
    padding:50px 20px;
    background:#050505;
    font-family:Arial,Helvetica,sans-serif;
  ">

    <div style="
      max-width:650px;
      margin:auto;
      background:#111111;
      border-radius:20px;
      overflow:hidden;
      border:1px solid #1f1f1f;
      box-shadow:0 20px 60px rgba(0,0,0,.45);
    ">

      <div style="
        background:#E50914;
        padding:30px;
        text-align:center;
      ">

        <h1 style="
          color:#fff;
          margin:0;
          font-size:32px;
          letter-spacing:2px;
        ">
          NEW SUBSCRIBER
        </h1>

      </div>

      <div style="padding:40px;">

        <h2 style="
          color:#ffffff;
          margin-top:0;
        ">
          🎉 Someone Joined Coveilla
        </h2>

        <p style="
          color:#d0d0d0;
          line-height:1.9;
          font-size:16px;
        ">
          A new visitor has subscribed to your newsletter.
        </p>

        <div style="
          background:#181818;
          border-left:4px solid #E50914;
          padding:20px;
          border-radius:10px;
          margin:30px 0;
        ">

          <p style="
            color:#999;
            margin:0;
            font-size:14px;
          ">
            Subscriber Email
          </p>

          <h3 style="
            color:#ffffff;
            margin:8px 0 0;
            font-size:20px;
          ">
            ${email}
          </h3>

        </div>

        <table style="
          width:100%;
          border-collapse:collapse;
          margin-top:20px;
        ">

          <tr>
            <td style="
              color:#888;
              padding:12px 0;
            ">
              Subscription Time
            </td>

            <td style="
              color:#fff;
              text-align:right;
            ">
              ${new Date().toLocaleString()}
            </td>
          </tr>

          <tr>
            <td style="
              color:#888;
              padding:12px 0;
            ">
              Source
            </td>

            <td style="
              color:#fff;
              text-align:right;
            ">
              Coveilla Newsletter
            </td>
          </tr>

        </table>

        <hr style="
          border:none;
          border-top:1px solid #222;
          margin:35px 0;
        ">

        <p style="
          color:#777;
          font-size:13px;
        ">
          This notification was automatically generated by the
          Coveilla Newsletter system.
        </p>

      </div>

    </div>

  </div>
  `;
};